// <auto-generated />
using System;
using Cliente_asp.net.MVC.core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cliente_asp.net.MVC.core.Migrations
{
    [DbContext(typeof(Cliente_aspnetMVCcoreContext))]
    [Migration("20200729035231_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cliente_asp.net.MVC.core.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cep");

                    b.Property<string>("Neighborhood");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Cliente_asp.net.MVC.core.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddresId");

                    b.Property<string>("BlockedFinancial");

                    b.Property<string>("Cnpj");

                    b.Property<string>("CompanyName");

                    b.Property<string>("FantasyName");

                    b.Property<string>("KindPerson");

                    b.Property<string>("MunicipalRegistration");

                    b.Property<string>("Name");

                    b.Property<string>("StateRegistration");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.HasIndex("AddresId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Cliente_asp.net.MVC.core.Models.Client", b =>
                {
                    b.HasOne("Cliente_asp.net.MVC.core.Models.Address", "Addres")
                        .WithMany()
                        .HasForeignKey("AddresId");
                });
#pragma warning restore 612, 618
        }
    }
}
